### ISSUE TITLE
Missing field for MOD inverter

### ISSUE THREAD

**Issue by wuschellux** [egguy/addon-grott-beta#22]
Hi,
I am using the MIN in inverter type configuration to monitor a MOD inverter with battery and smart-meter. So far I get data but some are missing:
- PV1 Energy - Today
- Load consumption
Is there a chance to get the values in?
Thanks and BR

<img width="379" alt="Bildschirmfoto 2024-01-30 um 09 51 17" src="https://github.com/egguy/addon-grott-beta/assets/63225276/6aefbdc1-28d8-431d-8ef7-fe9dfb05eede">

**Comment by fberoy-unedbarbastro** [comment]
Hello,
I'm in a similar situation. I have a MIN 3000 TL-XH, and installed the grott addon to version 2.8 with the following settings: Inverter Type: min - gmode: proxy - Enable grott MQTT - Active MQTT retain - Home Assistant plugin > off
![image](https://github.com/egguy/addon-grott-beta/assets/78879843/df85ddef-6e39-4ec2-b2b7-465bde78caef)

In my case I don't have batteries, although I have the sensors, but I don't see an Load Consumption sensor, nor import from or export to grid.
![image](https://github.com/egguy/addon-grott-beta/assets/78879843/80d5238b-5c78-4eb7-aa42-7a6a937eff34)
![image](https://github.com/egguy/addon-grott-beta/assets/78879843/0dd69696-2778-4767-8365-ff57d0c6657a)
![image](https://github.com/egguy/addon-grott-beta/assets/78879843/1a96a3a4-c427-4e6e-871b-1d0e067ce9a5)
