### ISSUE TITLE
Unexpected drop in reported solar production

### ISSUE THREAD

**Issue by kcleong** [egguy/addon-grott-beta#54]
As I noted in another issue the 'server IP' was changed which caused the local logging to stop. In my local network I added an DNS entry to force `server.growatt.com` to report to my HA instance.

<img width="595" alt="Screenshot 2024-07-18 at 19 42 54" src="https://github.com/user-attachments/assets/1a5d393f-55fc-4d51-b139-fcfa02a87d93">

After I added this 'fix' I thought all was well because data from the inverter was coming into HA. However since three days the reported solar production has one or twice a day an unexpected drop. As this is a cumulative value a drop should not happen.

<img width="1131" alt="Screenshot 2024-07-18 at 19 49 58" src="https://github.com/user-attachments/assets/4a553e6b-3507-4ddd-a62b-10f9c38a2d2b">

<img width="1412" alt="Screenshot 2024-07-18 at 19 39 48" src="https://github.com/user-attachments/assets/7f738c88-98dc-4329-b5dc-5942cd9d1607">

Wattage over time seems normal, some disruptions due the wrong reporting host on the 16th and 17th:

<img width="1406" alt="Screenshot 2024-07-18 at 19 41 22" src="https://github.com/user-attachments/assets/6e3b4842-a09b-4ceb-8e5b-e131f30fd81e">

What could be wrong in my set-up?

**Comment by egguy** [comment]
This is interesting, but I don't have an idea about this. the plugin mostly report the values sent by HA and subsequently the stick.

Does your interver turn off when there is no solar?
