### ISSUE TITLE
Instalation 2 days ego stopped sending data to HA

### ISSUE THREAD

**Issue by JacekJI** [egguy/addon-grott-beta#55]
- Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.3', 5279), raddr=('192.168.1.108', 45262)>

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.3', 5279), raddr=('192.168.1.108', 45262)>

	 - Growatt packet received:
		  <socket.socket fd=5, family=2, type=1, proto=0, laddr=('172.30.33.3', 5279), raddr=('192.168.1.108', 45262)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>

	 - Growatt packet received:
		  <socket.socket fd=4, family=2, type=1, proto=0, laddr=('172.30.33.3', 37144), raddr=('47.91.67.66', 5279)>
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Grott Beta branch (2.8)
 The Growatt inverter monitor with current HA plugin integrated
-----------------------------------------------------------
 Add-on version: 0.1.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.7.2
 Home Assistant Supervisor: 2024.06.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting

s6-rc: info: service legacy-services successfully started
[20:03:50] INFO: Preparing to start...
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Grott Growatt logging monitor : 2.8.2

Grott process configuration file

Grott process environmental variables

	Pulled 'ginvtype=default' from the environment

	Pulled 'gnomqtt=True' from the environment

	Pulled 'gextension=True' from the environment

	Pulled 'gextname=grottext.ha' from the environment

	Pulled 'gextvar={"ha_mqtt_host": "core-mosquitto", "ha_mqtt_port": "1883", "ha_mqtt_user": "addons", "ha_mqtt_password": "Aichoohau2zei4ohcheeghee0ne5ooth2aciuphieF6feiP6yee1shoo1agh4Oba", "ha_mqtt_retain": False}' from the environment

Grott override settings if set in commandline

Grott process json layout files

Grott proxy mode started
	 **********************************************************************************
	 - Grott - libscrc not installed, no CRC checking only record validation on length!
	 **********************************************************************************
Hostname : 8ce4abae-grott-current
IP :  172.30.33.3 , port :  5279 

All sensors are not-known
On the shine phone app workin fine and on the growatt web,

I didn't change anything

**Comment by typxxi** [comment]
You might also move ahead and leave the beta you are still using behind cause Johan has released 
GROTT 2.8.3 stable in may 2024 and then egguy followed with
GROTT stable 2.8.3 and his codeversion 0.1.10 while thise current one , the beta, will stay at the outdated 0.1.07 stage  I guess.

There is a migration described if you check the issues of this beta addon which now should be the second open issue when another guy had troubles with his version. I had written a migration path there cause I became aware of the new "stable" version as the master branch yesterday and there were a few steps which were quite new for me like installing both in parallel which is possible and usefull just to install the code and copy and paste the configuration of the beta to the stable one to then stop the beta and start the stable but after you have done a full backup of HA before.

That is the description in short and I hope you will get the message to get the stable version sooner than later.
