### ISSUE TITLE
what code base is addon-grott-beta relying and more open questions

### ISSUE THREAD

**Issue by typxxi** [egguy/addon-grott-beta#61]
Hi,
I had to fight a lot with the growatt deleted the grott ip in the wifi sticks adventure cause I was not aware of what was going on cause at the exact same time I had a maintenance week for my 8 inverters and got a new second distribution board and a complete AC re-wiring, then a new LAN cable and switches plus WLAN repeaters.

And when I came back with all my inverters everything was gone. And I had thought it must have been my fault cause the inverters were off grid and offline during all the rewiring. I had no clue what was going on except the growatt sensors were dead or depreciated and showed me a warning. Then I found out that the datalogger IP settings had been deleted which I had assumed was caused by the off grid situation for days. 

Long story short it took me days or roughly a week to get behind and find the solution which seems to be reliable: I reentered the IP adresse in the datalogger and then had set the ggrowattip to 8.209.71.240
Growatt is no longer deleting my settings and I can still edit my settings of the SPH inverter especially discharging schedules and so on.

BUT: during all the mess when I was not aware what was going on I wondered about the basics like who can help me and what information would be needed. And of cause which version are you running was one of the first. 
I had thought for whatever reason and believed I was running grott 2.8.3 as latest release but IS THAT REALLY true ?

And this is the weak or inconsistent point at least right now for me:

I have opened Grott addon and found this
![image](https://github.com/user-attachments/assets/b03f4c9f-060c-439c-a3f9-bc2d98ed9315)

And now I am wondering what is wrong: Am I running grott 2.8.3 or just 2.8 ?
Big differences regarding the support of different new inverters but I am not sure.

Then there is the second line called "Current version 0.1.7" with a link to a change log but also a lot more times where you simply find "grott 2.8"
I suggest to reduce how often you mention the version cause you would have to maintain that too, over time a lot of work if you wanna change that everywhere.
I am assuming that this grott ha is already 2.8.3 cause all the new min sph and what not invertermodels are implemented in this addon which grott has released with 2.8.3  I guess - not sure, but I believe there was a major change.

Finally I like the 1.0.7 in the second line and the change log but I miss that same number here on github cause I could not find that or overlooked that. 

But again the whole thing becomes confusing cause if I look on the top of this page I can read
"egguy / addon-grott-beta"
and if I open the [main page](https://github.com/egguy/addon-grott-beta) what do I have to read there ?

Grott beta 2.8.x

It is time to find a less confusing naming sheme used everywhere which clearly shows the roots, history and where it is like 

"GROTT BETA 2.8.3 - The HA ADD ON V1.0.7"
Not 2.8.x which is confusing if Grott is 2.8.1 or 2.8.2 or 2.8.3 cause people will ask Johan for advice like I did and he will ask first WHICH version and of cause I told him "2.8.3" in my deepest believe but I am still not sure if that is true or not.

And then all the references like "addon is based on the 2.8 Branch of [grott](https://github.com/johanmeijer/grott)" is obsolete cause the root and the right version are part of the project title. 

Side node: on that Grott beta 2.8.x page there you can find this line
"The grott server decodes them andsendsd them to your HA instance." 
where I suggest to correct the "andsendsd" to "and sends" plus to mention also mqtt as the transmitter and receiver cause right now grott server is handing those data over to mqtt and the sending is done by mqtt.

Tiny point but important for newbies to understand that this essential element mqtt is mentioned in the big picture. Otherwise you would not know about mqtt till you end in the configuration. 

I know these are tiny points but I guess it is time to take care for these especially in times when things had gone wrong and nothing seems to work anymor where everyone is searching for advice and solutions. 

You have achieved a lot and there are just tiny bits / pieces missing like using the same term every time like 2.8.3 instead of 2.8.x and so on. 
Great progress regarding the updates that came along with 1.0.7

**Comment by typxxi** [comment]
And from the HA point of view it is again different.

Here the grott addon opening page
![image](https://github.com/user-attachments/assets/3921257e-7488-44b0-bc0b-5342f19ffa95)

GROTT BETA branch (2.8)

3rd line mentions in german "for more infos look on the GROTT BETA branch (2.8)"
which looks nice until you open the link and end up here addon-grott-beta

![image](https://github.com/user-attachments/assets/01481881-299f-4f8f-b04e-90a08d2b9142)

Now back to HA and the other tabs, lets start with the last one protocol maybe in english log page and that looks nice too cause it uses the same term
![image](https://github.com/user-attachments/assets/7e7e35be-f3bc-414f-ab01-3e58ea726d5a)

"GROTT BETA branch (2.8)"

Then lets go back to configuration and be happy cause again a "GROTT BETA branch (2.8)" page.

But if you open the documentation you might feel to be in a different garden cause of this
"Grott - Home Assistant native MQTT integration"

No, we are on "GROTT BETA branch (2.8)"
and then the explanation can start with HA native mqtt integration.

That is confusing in an already very complicated topic with intercepting data to hand those over to mqqt as a middleman to get the data into HA sensors / entities while also providing a bidirectional communication door for growatt china which means to send the intercepted messages to china and open the gates for any replies or actions to be done on the growatt datalogger sticks or on the inverters. 

And then we have GROTT on top which was a long time 2.8.3 beta and has become the new stable in may 2024 while in parallel the "same implimentation" was available for Home Assistant owners that wann run that grott server on the same machine. 

And the final piece of code is your plugin or the muppet3000 Grott HA integration. 

THerefore it is time for a very precise terminology what is called how and in which version cause on github the issues go all over the places. Muppets page is full of issues that belong to grott native or to the grott beta branch addon. 

I really would appreciate that the whole process each "puzzle piece" name finding can be more streamlined and especially for the future with 2 major developements coming at least what I know about:

grott 3.0 standalone server if I am right (cause Johan had mentioned that he is busy working on that when the wifi stick story popped up 2 weeks ago).

and 

Chris / muppet3000 working on bidirectional "gateway" communication to also set registers of the inverter directly which is needed for the whole energy automation thing.

Time to streamline the current "line up" and especially all the future ones regarding 
- Grott 3
- Grott 3 for HA 
   (as I would call it cause it says what it is while Grott 3 HA addon is not self explaining to all who are new in this arena)
- Grott 3 - HA Sensor Management
- Grott 3 - HA Inverter Management

I am not sure if all of that is right or not, but for me it looks like this could be the situation in 2025 and therefore I suggest a rather simple name sheme to make things easier for all the user and the list of issues. I have reported some issues on Johans Grott page that might belonged here to the HA version cause I was again not aware of that I was on the grott add on beta branch 

where again the final question pops up why this one has the "beta branch" in the title while Johan has left it if I have gotten that 2.8.3 release right. But I am not sure who or what is beta and not but it is not the best idea to rely on a piece of code with "beta" in the title. 

Again: this i not about this code only but the whole GROTT picture and its future and therefore you might initiate a process how to deal with that in the future to get a clearer, better picture and overview about the whole Growatt inverter situation. 
Would help us all if issues are created where they belong. And also it might be time to open a discussion page for topics that might be or are no issues where the community can support other users too, also a kind of guidelines everyone wants and needs in the beginning. THANKS A LOT

**Comment by egguy** [comment]
Hi,

I apologise for the confusing situation about the grott version, I'm trying to track the current version
So the add-on is using the commit version to generate the add-on, you can find the version here: https://github.com/egguy/addon-grott-beta/blob/main/grott-beta/Dockerfile#L5

If you look at the last commit message of this version : https://github.com/johanmeijer/grott/tree/c97bd8ca8c6b8dd778cd3a089711703e0a60bd7e it is noted 2.8.3.
The grott stable version (which is also the version 2.8.3) is using: https://github.com/johanmeijer/grott/tree/f52ece051b17efd4a1f57fa8a3e0d6cfeca5adf5

There was the grott-stable and beta a one point because there were 2 branch (2.7 and 2.8) but now there is only 2.8 so they are mostly identical. Thanks for showing me there is a new release. I will update to the most recent code.

For the grott-HA plugin, this has also changed, as it is now a pypi library and not just a copy and paste: https://pypi.org/project/grott-ha-plugin/ the correct version is 0.11.0. This part interprets the decode JSON from grott and generates directly the devices in a HA MQTT devices.

So to resume:
- The code is at a "2.8.3" version (I would love tagged version, but it is not available)
- The grott HA plugin : 0.11.0
- The HA addon: 0.1.7 (package grott "2.8.3" and grott-ha plugin 0.11.0, plus bugfix of the container).

I will update the doc to correct the typo

**Comment by egguy** [comment]
I will try to take into account what you are suggesting, but it is probably going to take a couple of weeks as I don't have a lot of time at the moment.

Meanwhile, you should switch to https://github.com/egguy/addon-grott/ as it is more up to date. The edge channel has not the latest **2.8.3** update. I will release it tomorrow as a tagged vesion.

PS: I'm open to contributions, especially documentation and screenshots ;)

**Comment by typxxi** [comment]
Hi Etienne,

thanks for all the explanations. 
I am not a developer and could not get deeper to reverse what is based on what. I simply trust your documentation but again the current situation was confusing.

I am thankfull for your quick and in depth reply. 
I am simply using what "HA is providing under the Add On". If there is an update I usually wait 2 weeks or 3 weeks and will then upgrade after a full back up to be able to recover.

I can wait for the updates in the documentation but I simply wanna make sure how important it is to have a clean and straight line. Avoid beta cause the average user is not the risk taker to trust a beta which is not a beta cause your part of the code would be stable I guess. 
And then stay with the versions that come with grott. 

I hope we will see
GROTT 3.0
GROTT 3.0 - HA Edition V 0.1.x incl. Plugin 
GROTT 3.0 - HA - SENSOR MANAGEMENT V 007 (by Chris aka muppet3000) 
and later 
GROTT 3.0 - HA - INVERTER MANAGEMENT

Simple and clean to explain for newbies: you have HA then go for all the HA stuff, otherwise Grott 3.0 is your first choice.

CAN YOU PLEASE HELP ME WITH THIS PART !?
Meanwhile, you should switch to https://github.com/egguy/addon-grott/ as it is more up to date. The edge channel has not the latest 2.8.3 update. I will release it tomorrow as a tagged vesion.

I have no clue what is wrong or what I have to change ?
Do I have a wrong addon repository ?
I have no clue where I had found or gotten that edge channel except you had provided a link once or it was public available?

I had followed your instructions months ago and it had been working so far till the "wifi stick IP deletion powered by Growatt" hit me hard.

UPDATE: I have found it by visiting the addon store and there I found a version 0.1.10 which looks quite different from the first look . I will do a backup now and then change the repository to

![image](https://github.com/user-attachments/assets/49f7a1d8-7587-4c58-aee2-04cb9029604e)


Regarding supporting you with some tasks: 
yes, I can do that but unfortunatelly not before next year cause I am still rebuilding a house and the solar power system was just 1 piece while I am now working on the heatpump, then the hot water heatpump and another split AC plus the whole management system for that.

Again: I will try to help you out with documentation and screenshots especially the variety of growatt inverters I have here and have a reminder put in place for january 2nd 2025 to get in touch with you.

**Comment by typxxi** [comment]
And finally: What about a discussion page on github to avoid the flood of open issues that never had been open issues like this one I guess ?

As a new users I tend to look first into the documentation, youtube and then dig into the open issues and look what is going on there. And therefore a clean and short list is better than a longer one with topics of low importance.
