### ISSUE TITLE
typo in the readme

### ISSUE THREAD

**Issue by typxxi** [egguy/addon-grott-beta#83]
Hi,

I came along and read the read me.

I guess you meant "It's an easy to use and configure add-on."
So change the first word and remove the double add-on and everyhtings is fine.
![image](https://github.com/user-attachments/assets/c714f5db-eda6-4c1e-9032-6e9550d9cd9b)

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
PR opened @typxxi  @egguy
