### ISSUE TITLE
No shutdown when the value drops to 0

### ISSUE THREAD

**Issue by delimedia** [egguy/addon-grott-beta#9]
I have a small big problem currently.
I have a Growatt MIC 600TL-X inverter.
It turns off the ShineWifi stick when the inverter turns itself off in the evening. 
Unfortunately Grott 2.7 still transmits the last wattage numbers to Growat and also to MQTT.  So it is not recognized that the inverter is off and the value should be 0.

What can I do?

**Comment by muhkuh666** [comment]
Have the same issue!

**Comment by Sorentino1964** [comment]
Ebenfalls gleiches Problem 
Wechselrichter Growatt 2500 TL

**Comment by egguy** [comment]
Hi, I think I found a way to make HA mark the sensor as `Unvailable` after not receiving updates.
@Schelin78 @muhkuh666 Could this work for you?

e.g.
![image](https://github.com/egguy/addon-grott-beta/assets/186777/c69e46b8-daf1-4817-a12f-0161c61bbb41)

**Comment by muhkuh666** [comment]
How to do so?

**Comment by egguy** [comment]
There is a parameter in the MQTT discovery who could be used to make the devices unavailable if there is no new value pushed after a certain time.
So when the inverter shutdown, the push of values cease and the devices would be marked as unavailable 15 minutes after.

I put 15 minutes to prevent transients problems.

If this is what you are looking for, I will push this in the next version of the addon.

**Comment by Sorentino1964** [comment]
That's it
That would be very nice if you could implement that

**Comment by egguy** [comment]
Hi @Sorentino1964 @muhkuh666 @Schelin78 @delimedia 

Finally! I found a bit of time to update. The addon has been published on the edge repository.

It is possible to stop the regular add-on and install the addon in the edge repository: https://github.com/egguy/ha-addons-edge/
You can copy the configuration of the old addon to the new in YAML mode.

Could you please confirm the addon works for you and does what you want? The expiration of the measures is after 15 minutes (2 default 5m period to prevent jitter + 1 of buffer).

If everything works, I will publish the add-on to the stable repo. Thanks for you feedback

**Comment by Sorentino1964** [comment]
Hi @egguy 
Today I installed the new Current version: 0.1.6.
I'll test it for a few days now and then report back.
Thank you again for your good work here.

**Comment by egguy** [comment]
Hi, the  1.6 doesn't include the changes for the moment I only pushed it on the edge branch. 

I didn't have time to make a proper release.

**Comment by Sorentino1964** [comment]
![Grott](https://github.com/egguy/addon-grott-beta/assets/134504073/4c105432-1920-442f-a029-aa0c8d8f87bc)

**Comment by Sorentino1964** [comment]
@egguy 
First test OK👌

**Comment by egguy** [comment]
Thank you for the test and feedback. I'm going to push it to the main branch.
